# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d87870ac3a3f2901fc1dc129028cfded5872d076a0bccd0d3ed5a71fda5fa01fc82aaa189640bb608265caf10351ff2f466be4f908eaf3525d7bf895d883716

test:
  secret_key_base: f62c129215014a38ea82e1fa86d01c333bfb029bb8edf48e75014ad93ecd8643037f57f2eba308b526fb880f93c3af7fbf9ed9a9ef414835220ec1c407fb209f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
